M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date sáb 06 may 2023 23:23:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-06T23:23:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.980
%
G90
G05
T1
X132.11Y-143.196
X137.89Y-143.196
T2
X110.65Y-109.2
T0
M30
